#ifndef _INFRA_CONFIG_H_
#define _INFRA_CONFIG_H_

#define PLATFORM_HAS_STDINT
#define PLATFORM_HAS_DYNMEM
#define PLATFORM_HAS_OS
#define INFRA_LOG
#define INFRA_LOG_ALL_MUTED
#define INFRA_LOG_MUTE_FLW
#define INFRA_LOG_MUTE_DBG
#define INFRA_LOG_MUTE_INF
#define INFRA_LOG_MUTE_WRN
#define INFRA_LOG_MUTE_ERR
#define INFRA_LOG_MUTE_CRT
#define INFRA_SHA256
#define DEV_SIGN
#define DEVICE_MODEL_CLASSIC

#endif
